Improve error handling.

diff --git a/opensubtitles-dl b/opensubtitles-dl
--- a/opensubtitles-dl
+++ b/opensubtitles-dl
@@ -42,6 +42,11 @@ do
         break
     fi
 done <<< "$zipinfo"
+if [ -z "${source_srt-}" ]
+then
+    printf '<%s>: subtitle file not found\n' >&2 "$dl_url"
+    exit 1
+fi
 unzip -p "$tmpdir/subtitles.zip" "$source_srt" > "$target_srt"
 rm -rf "$tmpdir"
 printf '%s -> %s\n' "$dl_url" "$target_srt" >&2
